### ISSUE TITLE
Getting an error when posting a new document

### ISSUE THREAD

**Issue by ReportCardsMC** [toptal/haste-server#382]
Whenever I send a POST request to add a new document (On multiple machines and IP's), I'm getting an error:

```cmd
Error: Service Unavailable
    at Object.exports.default (C:\Users\#####\Documents\GitHub\HytaleNewsBOT\dist\utils\hastebin\hastebin.js:17:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async MessageBulkDelete.exec (C:\Users\#####\Documents\GitHub\HytaleNewsBOT\dist\listeners\ModLogs\MessageBulkDelete.js:41:21)```

**Comment by Aliraza2686** [comment]
For ease of use, would it be possible to have an official dockerhub implementation?

**Comment by konstrybakov** [comment]
It would be easier to understand your issue if you would provide a bit more context.  A reproduction possibly?

**Comment by ReportCardsMC** [comment]
> It would be easier to understand your issue if you would provide a bit more context. A reproduction possibly?

Honestly I completely forgot about this issue, I've fixed it since then, I think it was an issue with how I was using CloudFlare, not specifically with haste-server
